unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LoanApplicationConditions__c/LoanApplicationConditions__c.object-meta.xml
<CustomObject>
    <label>Loan Application Condition</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Application Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LoanApplicationConditions__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Loan Application Conditions</relationshipLabel>
    <relationshipName>LoanApplicationConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LoanApplicationConditions__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/LoanApplicationConditionsTriggerTest.cls
@isTest
private class LoanApplicationConditionsTriggerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.initApplicationSettings();
        Account individual = TestDataFactory.createPersonAccount('Seth', 'Testing', 'testing@verteva.com.au', '456456456');
        Application__c application = TestDataFactory.createApplication(individual.Id);
        TestDataFactory.createFinancials(application.Id);
        TestDataFactory.createFoldersForBucket('nanotest');
    }

    @isTest
    static void testExtId() {
        LoanApplicationConditions__c lap = new LoanApplicationConditions__c(
            Application__c = [Select id from application__c limit 1].id
        );

        insert lap;

        System.assert(String.isNotBlank([SELECT ExternalId__c FROM LoanApplicationConditions__c WHERE Id = :lap.Id].ExternalId__c));
    }
}