unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXC-{0000}</displayFormat>
        <label>Exception Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ExceptionLog__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Exception Logs</relationshipLabel>
    <relationshipName>ExceptionLogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ExceptionLogTriggerHandlerTest.cls
@istest 
private class ExceptionLogTriggerHandlerTest {
    

    @TestSetup
    static void createFinancials(){
        TestDataFactory.initApplicationSettings();
        Account individual = TestDataFactory.createPersonAccount('Seth', 'Testing', 'testing@verteva.com.au', '456456456');
        Application__c application = TestDataFactory.createApplication(individual.Id);
        
    }

    @IsTest
    static void testExceptionMapping(){
        Test.startTest();

            String exceptionCode = 'VAL-1234';

            Application__c app = [select id from application__c limit 1];
            TestDataFactory.createChecklistConfig(exceptionCode);
            ExceptionLog__c el = TestDataFactory.createApplicationException(app.id, 'valuation error', exceptionCode);

        Test.stopTest();

        System.assertEquals([select id from Task where whatId = :app.id].size() != 0 , true);
        
    }



}