unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicationChecklistConfiguration__c/ApplicationChecklistConfiguration__c.object-meta.xml
<CustomObject>
    <description>Object to manage the Exception handling</description>
    <label>Application Checklist Configuration</label>
    <nameField>
        <displayFormat>ACC-{0000}</displayFormat>
        <label>Application Checklist Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Checklist Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicationChecklistConfiguration__c/fields/ExceptionCode__c.field-meta.xml
<CustomField>
    <fullName>ExceptionCode__c</fullName>
    <label>Exception Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXC-{0000}</displayFormat>
        <label>Exception Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ExceptionLog__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Exception Logs</relationshipLabel>
    <relationshipName>ExceptionLogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ExceptionLog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Exception Description</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ExceptionLog__c/fields/ExceptionCode__c.field-meta.xml
<CustomField>
    <fullName>ExceptionCode__c</fullName>
    <label>Exception Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TaskTemplate__c/TaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Task Creation</description>
    <label>Task Template</label>
    <nameField>
        <displayFormat>TASK-{0000}</displayFormat>
        <label>TaskTemplate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TaskTemplate__c/fields/ApplicationChecklistConfiguration__c.field-meta.xml
<CustomField>
    <fullName>ApplicationChecklistConfiguration__c</fullName>
    <label>Application Checklist Configuration</label>
    <referenceTo>ApplicationChecklistConfiguration__c</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/TaskTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/TaskTemplate__c/fields/DueIn__c.field-meta.xml
<CustomField>
    <fullName>DueIn__c</fullName>
    <description>Number of days from today</description>
    <inlineHelpText>Number of days from today</inlineHelpText>
    <label>Due In</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/TaskTemplate__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TaskTemplate__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ExceptionLogTriggerHandler.cls
public with sharing class ExceptionLogTriggerHandler extends TriggerHandler {
    
    private Map<Id, ExceptionLog__c> newExceptionsMap;

    public ExceptionLogTriggerHandler(){
        this.newExceptionsMap = (Map<Id, ExceptionLog__c>) Trigger.newMap;
    }

    public override void afterInsert() {
        
        ExceptionLogTriggerHandler.createApplicationTasks( this.newExceptionsMap.keyset() );

    }


    @future
    private static void createApplicationTasks( Set<Id> exceptionIds ){
        List<Task> newTasks = new List<Task>();
        Set<String> exceptionCodes = new Set<String>();

        List<ExceptionLog__c> newExceptions = [ SELECT   Id, ExceptionCode__c, Application__c, Application__r.OwnerId 
                                                FROM     ExceptionLog__c 
                                                WHERE    ID = :exceptionIds 
                                                ORDER BY ExceptionCode__c];

        
        for( ExceptionLog__c e : newExceptions )
            exceptionCodes.add( e.ExceptionCode__c );
        
        if(!exceptionCodes.isEmpty()){
            
            List<TaskTemplate__c> taskTemplates = [ SELECT  ID, ApplicationChecklistConfiguration__r.ExceptionCode__c, Subject__c, Priority__c, Description__c, DueIn__c
                                                    FROM    TaskTemplate__c
                                                    WHERE   ApplicationChecklistConfiguration__r.ExceptionCode__c in :exceptionCodes
                                                    ORDER BY ApplicationChecklistConfiguration__r.ExceptionCode__c ];

            for( ExceptionLog__c exc : newExceptions )
                for( TaskTemplate__c taskTemplate : taskTemplates )
                    if( exc.ExceptionCode__c == taskTemplate.ApplicationChecklistConfiguration__r.ExceptionCode__c ) {
                        newTasks.add( 
                            new Task( 
                                WhatId = exc.Application__c,
                                OwnerId = exc.Application__r.OwnerId,
                                Subject = taskTemplate.Subject__c,
                                Description = taskTemplate.Description__c,
                                Priority = taskTemplate.Priority__c,
                                ActivityDate = System.today().addDays( Integer.valueOf( taskTemplate.DueIn__c ) ),
                                Status = 'Not Started'
                            )    
                        );
                    }
                
            
            system.debug( newTasks );
            insert newTasks;


        }
        

    }
    

}