unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conversion_Mapping__c/Conversion_Mapping__c.object-meta.xml
<CustomObject>
    <description>This object is meant for the conversion mapping information for all the fields of the application and its children to loan account and its children respectively. Refer to particular fields for their description and populate the values carefully.</description>
    <label>Conversion Mapping</label>
    <nameField>
        <displayFormat>CMV-{0000}</displayFormat>
        <label>Conversion Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversion Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <description>This field is meant for providing default values for some fields on the loan account object. It only works if the Target Object(loan__Loan_Account__c) and Field values are populated.</description>
    <inlineHelpText>This field is meant for providing default values for some fields on the loan account object. It only works if the Target Object(loan__Loan_Account__c) and Field values are populated.</inlineHelpText>
    <label>Default Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>This field is only reserved for the child objects at the source level and carries the API name of the application lookup on them. So that we could query those child records such as applicants, rate schedules and properties corresponding the application we are converting.</description>
    <inlineHelpText>This field is only reserved for the child objects at the source level and carries the API name of the application lookup on them. So that we could query those child records such as applicants, rate schedules and properties for the app.</inlineHelpText>
    <label>Filter Criteria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field specified if the target field is required to be populated.</description>
    <inlineHelpText>This field specified if the target field is required to be populated.</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>API name of the target’s parent’s lookup. This field is only reserved for the target’s child records such as rate schedules, collaterals and parties.</description>
    <inlineHelpText>API name of the target’s parent’s lookup. This field is only reserved for the target’s child records such as rate schedules, collaterals and parties.</inlineHelpText>
    <label>Parent Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <description>The API name of the field which will be mapped to the target field on the target object.</description>
    <inlineHelpText>The API name of the field which will be mapped to the target field on the target object.</inlineHelpText>
    <label>Source Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API name of the source object, whether it's a parent or a child object.</description>
    <inlineHelpText>The API name of the source object, whether it's a parent or a child object.</inlineHelpText>
    <label>Source Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The API name of the field which will be mapped from the source field on the source object.</description>
    <inlineHelpText>The API name of the field which will be mapped from the source field on the source object.</inlineHelpText>
    <label>Target Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <description>The API name of the target object, whether it's a parent or a child object.</description>
    <inlineHelpText>The API name of the target object, whether it's a parent or a child object.</inlineHelpText>
    <label>Target Object</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ConvertAppToContractCtlr.cls
global class ConvertAppToContractCtlr{

    @InvocableMethod(label='Convert Application' description='Convert a given application id to a Loan Account' category='Application')
    public static void convertApplication(List<ID> ids) {

        if(ids != null && !ids.isEmpty())
            new ConvertAppToContractCtlr(ids.get(0));
        

    }
    
    global ConvertAppToContractCtlr(Id ApplicationId){
        //initialize Application data and mapping data
        List<Conversion_Mapping__c> conversionMappings = [Select id,Name,
                                                                Mandatory__c,
                                                                Parent_Object__c,
                                                                Source_Field__c,
                                                                Source_Object__c,
                                                                Target_Field__c,
                                                                Target_Object__c,
                                                                Default_Value__c,
                                                                Filter_Criteria__c
                                                           From Conversion_Mapping__c];
        //validate conversion mapping
        if(conversionMappings.size() > 0){
            
            if(validateConversionMapping(conversionMappings)){
                Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
                SObjectType currentObject = gd.get('Application__c');
                Map<String, Schema.SObjectField> allFields = currentObject.getDescribe().fields.getMap();
                mfiflexUtil.ExecutionContext ec = mfiflexUtil.ExecutionContext.getExecContext();
                mfiflexUtil.ObjectCache entries = ec.createObject('Application', 'Application__c', true);
                for(String field: allFields.keyset()) {
                entries.addFields(field);
                }
                entries.addNamedParameter('appID', ApplicationId);
                entries.setWhereClause('Id = :appID');
                entries.buildQuery();
    
                System.debug('Dynamic Query :'+ entries.getQuery());
                Application__c applicationinstance = ((List<Application__c>) entries.executeQuery().getRecords()).get(0);
                
                //calling the handler class
                ConvertAppToContractHandler handler = new ConvertAppToContractHandler(applicationinstance, conversionMappings);              
            }
        }else{
            system.debug('Conversion mapping doesn\'t exist');
            throw new IllegalArgumentException('Conversion mapping doesn\'t exist');
        }
    }    
        global Boolean validateConversionMapping(List<Conversion_Mapping__c> conversionMapping){
            Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
            for(Conversion_Mapping__c cm :conversionMapping){
                if(cm.Default_Value__c == null && (cm.Source_Object__c == null || cm.Target_Object__c == null || cm.Source_Field__c == null || cm.Target_Field__c == null)){
                    //this should not arise
                    
                    system.debug('Value not defined properly, please check the mapping named:' + cm.Name);
                        throw new IllegalArgumentException('Value not defined properly, please check the mapping named:' + cm.Name);
                }else{
                    if(cm.Default_Value__c == null && !gd.containsKey(cm.Source_Object__c)){
                        //this should not arise
                        system.debug('Value not defined properly, please check the source object name for mapping named:' + cm.Name);
                        throw new IllegalArgumentException('Value not defined properly, please check the source object name for mapping named:' + cm.Name);
                    }else if(cm.Default_Value__c == null){
                        SObjectType currentObject = gd.get(cm.Source_Object__c);
                        Map<String, Schema.SObjectField> allFields = currentObject.getDescribe().fields.getMap();
                        if(!allFields.keySet().contains(cm.Source_Field__c.toLowerCase())){
                            system.debug(currentObject);
                            system.debug(allFields.keySet());
                            system.debug('Value not defined properly, please check the source field name for mapping named:' + cm.Name);
                            throw new IllegalArgumentException('Value not defined properly, please check the source field name for mapping named:' + cm.Name);
                        }
                    }
                    if(!gd.containsKey(cm.Target_Object__c)){
                        //this should not arise
                        system.debug('Value not defined properly, please check the target object name mapping named:' + cm.Name);
                        throw new IllegalArgumentException('Value not defined properly, please check the mapping');
                    }else{
                        SObjectType currentObject = gd.get(cm.Target_Object__c);
                        Map<String, Schema.SObjectField> allFields = currentObject.getDescribe().fields.getMap();
                        if(!allFields.keySet().contains(cm.Target_Field__c.toLowerCase())){
                            system.debug('Value not defined properly, please check the source field name for mapping named:' + cm.Name);
                            throw new IllegalArgumentException('Value not defined properly, please check the source field name for mapping named:' + cm.Name);
                        }
                    }
                }    
        }
        return true;
    }    
}