unpackaged/main/default/objects/ApplicantIdentity__c/ApplicantIdentity__c.object-meta.xml
<CustomObject>
    <label>Applicant Identity</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Applicant Identity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Identities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantIdentity__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ApplicantIdentityTriggerTest.cls
@isTest
private class ApplicantIdentityTriggerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.initApplicationSettings();
        Account individual = TestDataFactory.createPersonAccount('Seth', 'Testing', 'testing@verteva.com.au', '456456456');
        Application__c application = TestDataFactory.createApplication(individual.Id);
        TestDataFactory.createFinancials(application.Id);
        TestDataFactory.createFoldersForBucket('nanotest');
    }

    @isTest
    static void testExtId() {
        ApplicantIdentity__c lap = new ApplicantIdentity__c();

        insert lap;

        System.assert(String.isNotBlank([SELECT ExternalId__c FROM ApplicantIdentity__c WHERE Id = :lap.Id].ExternalId__c));
    }
}