unpackaged/main/default/objects/ApplicationSettings__c/ApplicationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Settings</label>
</CustomObject>

unpackaged/main/default/objects/ApplicationSettings__c/fields/CalloutIntervalWait__c.field-meta.xml
<CustomField>
    <fullName>CalloutIntervalWait__c</fullName>
    <defaultValue>120</defaultValue>
    <label>CalloutIntervalWait (Seconds)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CalloutWrapper.cls
public with sharing class CalloutWrapper {
    
    @AuraEnabled
    public static String makeCallout( String serviceName, String guid ){
        
        try {

            HTTPResponse response = OnboardingServices.makeCallout( serviceName, guid );
            return JSON.serialize(
                new Map<String, String>{ 
                    'status' => String.valueOf(response.getStatusCode()),
                    'message' => response.getBody()
                }
            );

        } catch (Exception e) {
            return JSON.serialize(
                new Map<String, String>{ 
                    'status' => '500',
                    'message' => e.getMessage()
                }
            );
        }
            
        
    }


    @AuraEnabled(cacheable=true)
    public static Integer getCalloutIntervalWait(){
        ApplicationSettings__c appSettings = ApplicationSettings__c.getOrgDefaults();
        return Integer.valueOf(appSettings.CalloutIntervalWait__c);
    }

    @AuraEnabled
    public static sObject getLatestRecord(String objectName, String fields, String filter){
        
        String query = 'SELECT ' + fields + ' FROM ' + objectName + getFilter(filter) + ' ORDER BY LastModifiedDate DESC LIMIT 1';
        system.debug(query);
        List<sObject> records = Database.query(query);
        system.debug(records);
        if(records.isEmpty())
            return null;
        else 
            return records[0];

    }

    private static String getFilter(String filter){
        return filter != null ? ' WHERE ' + filter : '';
    }



}