unpackaged/main/default/objects/ApplicationSettings__c/ApplicationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Application Settings</label>
</CustomObject>

unpackaged/main/default/objects/ApplicationSettings__c/fields/Objects__c.field-meta.xml
<CustomField>
    <fullName>Objects__c</fullName>
    <description>a comma separated list of object api names that have to be scanned through for enums and have their values send via rest api to external apps</description>
    <inlineHelpText>a comma separated list of object api names that have to be scanned through for enums and have their values send via rest api to external apps</inlineHelpText>
    <label>Objects</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/classes/WSApplicationEnums.cls
@RestResource(urlMapping='/v1/Application/Enums')
global without sharing class WSApplicationEnums {

    @HTTPGet
    global static void getApplicationEnums(){

        ApplicationSettings__c settings = ApplicationSettings__c.getOrgDefaults();
        RestResponse res = RestContext.response;
        
        if(settings != null && settings.Objects__c != null){
            res.statusCode = 200;
            res.responseBody = Blob.valueOf( JSON.serialize( OnboardingServices.getPicklistValuesByObjects(settings.Objects__c.split(',')) ) );
        } else {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf( 'There\'s an application configuration error in Salesforce.');
        }

        
    }

    
}