unpackaged/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/Conversion_Mapping__c.object-meta.xml
<CustomObject>
    <description>This object is meant for the conversion mapping information for all the fields of the application and its children to loan account and its children respectively. Refer to particular fields for their description and populate the values carefully.</description>
    <label>Conversion Mapping</label>
    <nameField>
        <displayFormat>CMV-{0000}</displayFormat>
        <label>Conversion Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversion Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>This field is only reserved for the child objects at the source level and carries the API name of the application lookup on them. So that we could query those child records such as applicants, rate schedules and properties corresponding the application we are converting.</description>
    <inlineHelpText>This field is only reserved for the child objects at the source level and carries the API name of the application lookup on them. So that we could query those child records such as applicants, rate schedules and properties for the app.</inlineHelpText>
    <label>Filter Criteria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field specified if the target field is required to be populated.</description>
    <inlineHelpText>This field specified if the target field is required to be populated.</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>API name of the target’s parent’s lookup. This field is only reserved for the target’s child records such as rate schedules, collaterals and parties.</description>
    <inlineHelpText>API name of the target’s parent’s lookup. This field is only reserved for the target’s child records such as rate schedules, collaterals and parties.</inlineHelpText>
    <label>Parent Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <description>The API name of the field which will be mapped to the target field on the target object.</description>
    <inlineHelpText>The API name of the field which will be mapped to the target field on the target object.</inlineHelpText>
    <label>Source Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API name of the source object, whether it's a parent or a child object.</description>
    <inlineHelpText>The API name of the source object, whether it's a parent or a child object.</inlineHelpText>
    <label>Source Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The API name of the field which will be mapped from the source field on the source object.</description>
    <inlineHelpText>The API name of the field which will be mapped from the source field on the source object.</inlineHelpText>
    <label>Target Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Conversion_Mapping__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <description>The API name of the target object, whether it's a parent or a child object.</description>
    <inlineHelpText>The API name of the target object, whether it's a parent or a child object.</inlineHelpText>
    <label>Target Object</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ConvertAppToContractCtlrTest.cls
/**
 * Created by Muhammad on 17/11/20.
 */

@IsTest
private class ConvertAppToContractCtlrTest {
    @IsTest
    static void testBehavior() {
        Account acc = TestDataFactory.createPersonAccount('Test','User','testUser@gmil.com','0345241312');
        Application__c app = TestDataFactory.createApplication(acc.Id);
        List<Id> ids = new List<Id>();
        ids.add(app.Id);
        Conversion_Mapping__c cm = new Conversion_Mapping__c(Target_Object__c = 'loan__Coborrower__c',Target_Field__c = 'loan__Account__c',Source_Field__c ='Account__c',Source_Object__c='Applicant__c',Parent_Object__c='loan__Loan__c',Mandatory__c=true,Filter_Criteria__c='Application__c');
        insert cm;
        try{
            ConvertAppToContractCtlr.convertApplication(ids);
        }catch(Exception e){
            System.debug(e.getMessage());
        }

    }
}