unpackaged/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ApplicantAddress__c/ApplicantAddress__c.object-meta.xml
<CustomObject>
    <label>Applicant Address</label>
    <nameField>
        <displayFormat>ADD-{0000}</displayFormat>
        <label>Applicant Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantAddress__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applicant Addresses</relationshipLabel>
    <relationshipName>ApplicantAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ApplicantAddress__c/fields/ResidenceType__c.field-meta.xml
<CustomField>
    <fullName>ResidenceType__c</fullName>
    <label>Residence Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Former Address</fullName>
            </value>
            <value>
                <fullName>Present Address</fullName>
            </value>
            <value>
                <fullName>Mailing Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ApplicantEmployment__c/ApplicantEmployment__c.object-meta.xml
<CustomObject>
    <label>Applicant Employment</label>
    <nameField>
        <displayFormat>AEM-{0000}</displayFormat>
        <label>Applicant Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantEmployment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applicant Employments</relationshipLabel>
    <relationshipName>ApplicantEmployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ApplicantIdentity__c/ApplicantIdentity__c.object-meta.xml
<CustomObject>
    <label>Applicant Identity</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Applicant Identity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Identities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantIdentity__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applicant Identities</relationshipLabel>
    <relationshipName>Applicant_Identities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ApplicantsController.cls
public with sharing class ApplicantsController {

    @AuraEnabled
    public static List<Applicant__c> getApplicants(String applicationId){

        return [SELECT  Id, Account__r.Name, Application__c, Application__r.SubmittedDate__c,
                        (SELECT    Id
                          FROM     ApplicantEmployments__r
                          ORDER BY CreatedDate DESC
                          LIMIT    1),
                        (SELECT    Id
                            FROM   ApplicantAddresses__r WHERE ResidenceType__c = 'Present Address'
                          ORDER BY CreatedDate DESC
                          LIMIT    1),
        (SELECT Id,Name FROM Applicant_Identities__r ORDER BY CreatedDate DESC)
                FROM    Applicant__c 
                WHERE   Application__c = :applicationId];
        
    }
}