unpackaged/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ApplicantAddress__c/ApplicantAddress__c.object-meta.xml
<CustomObject>
    <label>Applicant Address</label>
    <nameField>
        <displayFormat>ADD-{0000}</displayFormat>
        <label>Applicant Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantAddress__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applicant Addresses</relationshipLabel>
    <relationshipName>ApplicantAddresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ApplicantEmployment__c/ApplicantEmployment__c.object-meta.xml
<CustomObject>
    <label>Applicant Employment</label>
    <nameField>
        <displayFormat>AEM-{0000}</displayFormat>
        <label>Applicant Employment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ApplicantEmployment__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Applicant Employments</relationshipLabel>
    <relationshipName>ApplicantEmployments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>PRO-{0000}</displayFormat>
        <label>Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Property__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Properties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/VertevaUtilsTest.cls
@isTest
private class VertevaUtilsTest {

    @IsTest
    static void setGUID(){
        Account acc = TestDataFactory.createPersonAccount('Testing', 'Test', 'testing@nano.com.au', '456456456');
        TestDataFactory.createCompleteApplication(acc.id);
        
        //assert guid here

        system.assertEquals( 
            String.isNotEmpty( [select ExternalId__c from Application__c limit 1].ExternalId__c ),
            true
        );

        system.assertEquals( 
            String.isNotEmpty( [select ExternalId__c from Property__c limit 1].ExternalId__c ),
            true
        );

        system.assertEquals( 
            String.isNotEmpty( [select ExternalId__c from Applicant__c limit 1].ExternalId__c ),
            true
        );

        system.assertEquals( 
            String.isNotEmpty( [select ExternalId__c from ApplicantAddress__c limit 1].ExternalId__c ),
            true
        );

        system.assertEquals( 
            String.isNotEmpty( [select ExternalId__c from ApplicantEmployment__c limit 1].ExternalId__c ),
            true
        );

    }   

    @istest
    private static void testMethodPositive(){
        String objectName = VertevaUtils.findObjectNameFromRecordIdPrefix('500');
        System.assertEquals(objectName,'Case');
    }
    @isTest
    private static void testMethodNegative(){
        String objectName = VertevaUtils.findObjectNameFromRecordIdPrefix('500');
        System.assertNotEquals(objectName,'Account');
    }
    @isTest
    private static void testMethodNull(){
        String objectName = VertevaUtils.findObjectNameFromRecordIdPrefix('101');
        System.assertEquals(objectName,'');
    }
    @isTest
    private static void testMethodException(){
        String objectName = VertevaUtils.findObjectNameFromRecordIdPrefix('10');
        System.assertEquals(objectName,'');
    }

    @isTest
    private static void testGetPicklistValues(){
        System.assertEquals(
            VertevaUtils.getPicklistValues('Account', 'AccountSource').size() != 0, 
            true
        );
        System.assertEquals(
            VertevaUtils.isEmpty( VertevaUtils.getSerializedPicklistValues('Account', 'AccountSource') ), 
            false
        );
    }


    
}