unpackaged/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Applicant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Asset</label>
    <nameField>
        <displayFormat>APA-{0000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Asset__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
                <default>true</default>
                <label>Real Estate</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Liability__c/Liability__c.object-meta.xml
<CustomObject>
    <label>Liability</label>
    <nameField>
        <displayFormat>LIA-{0000}</displayFormat>
        <label>Liability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Liability__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liabilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Liability__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Liabilities</relationshipLabel>
    <relationshipName>Liabilities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Liability__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Personal loan</fullName>
            </value>
            <value>
                <fullName>Vehicle loan</fullName>
                <label>Vehicle loan (e.g. car or boat)</label>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Credit card</fullName>
            </value>
            <value>
                <fullName>Lines of credit</fullName>
            </value>
            <value>
                <fullName>Store card</fullName>
            </value>
            <value>
                <fullName>Overdraft</fullName>
            </value>
            <value>
                <fullName>Margin loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FinancialsControllerTest.cls
@isTest 
private class FinancialsControllerTest {
    
    @TestSetup
    static void createFinancials(){
        TestDataFactory.initApplicationSettings();
        Account individual = TestDataFactory.createPersonAccount('Seth', 'Testing', 'testing@verteva.com.au', '456456456');
        //loan__Loan_Product__c lendingproduct = TestDataFactory.createlendingproduct(); 
        Application__c application = TestDataFactory.createApplication(individual.Id);
        TestDataFactory.createFinancials(application.Id);
    }

    @isTest
    static void testRetrieveFinancials(){
        Application__c app = [select id, name from application__c limit 1];
        Application__c testApp = FinancialsController.getApplication(app.id);

        //assert application
        System.assertEquals(app.Name, testApp.Name);

        //assert assets
        System.assertEquals(String.isNotBlank(FinancialsController.getAssets(app.id)), true);

        //assert liabilities
        System.assertEquals(String.isNotBlank(FinancialsController.getLiabilities(app.id)), true);

        //assert expenses
        System.assertEquals(String.isNotBlank(FinancialsController.getExpenses(app.id)), true);

        //assert incomes
        System.assertEquals(String.isNotBlank(FinancialsController.getIncomes(app.id)), true);
    }

    @isTest
    static void testSaveFinancials(){
        Application__c app = [select id, name from application__c limit 1];

        String payload = FinancialsController.getAssets(app.id);
        system.debug(payload);
        List<FinancialsController.FinanceRecord> financeRecords  = (List<FinancialsController.FinanceRecord>) JSON.deserialize(payload, List<FinancialsController.FinanceRecord>.class);

        for(FinancialsController.FinanceRecord fr : financeRecords){
            fr.detail.put('AssessedNotes__c', 'APEXTESTING');
            fr.hasChanged = true;
        }
        FinancialsController.saveFinanceRecords( JSON.serialize( financeRecords ) );

        for(Asset__c updatedAsset : [SELECT AssessedNotes__c FROM Asset__c])
            system.assertEquals(updatedAsset.AssessedNotes__c, 'APEXTESTING');

    }


    @isTest
    static void testSaveNewAsset(){
        Application__c app = [select id, name, (select id from applicants__r) from application__c limit 1];
        Map<String, Object> payload = new Map<String, Object>{
            'applicationId' => app.id,
            'applicantId' => (app.Applicants__r.size() > 0 ? app.Applicants__r[0].id : null),//todo: remove checking applicant array
            'unitNumber' => '22',
            'streetNumber' => '100',
            'streetType' => 'Street',
            'streetName' => 'George',
            'suburb' => 'CBD',
            'postalCode' => '2000',
            'city' => 'Sydney',
            'state' => 'NSW',
            'country' => 'Australia',
            'propertyValue' => '2500009',
            'loanNotes' => 'assessed notes',

            'hasLoan' => 'true',

            'class' => VertevaUtils.getPicklistValues('Liability__c', 'Class__c')[0].getValue(),
            'loanMonthlyRepayments' => '5000',
            'loanBalance' => '500000',
            'loanNotes' => 'assessed notes',

            'hasRentalIncome' => 'true',

            'monthlyRentalIncome' => '2500',
            'incomeNotes' => 'rent notes'

        };

        FinancialsController.saveNewAsset(JSON.serialize(payload));



    }



    @isTest
    static void testServiceability(){
        
        Application__c app = [select id, name, (select id from applicants__r) from application__c limit 1];
        Map<String, Decimal> calc = FinancialsController.getServiceabilityCalc(app.id);

        system.assertEquals(calc !=  null, true);
        system.assertEquals(calc.get('surplusBalance') !=  null, true);
        system.assertEquals(calc.get('basiq') !=  null, true);
        system.assertEquals(calc.get('applicant') !=  null, true);
        system.assertEquals(calc.get('assessed') !=  null, true);
    }

}